---
# tasks file for flatpaks

- name: Remove the Fedora flatpak repo
  community.general.flatpak_remote:
    name: fedora
    state: present
  become: yes

- name: Add Flatpak remote for Flathub
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    method: user
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_remote_install }}"

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item.package }}"
    state: present
    method: user
    remote: "{{ item.remote }}"
  loop: "{{ flatpak_package_install }}"

